### ISSUE TITLE
Maintain order after reloading results

### ISSUE THREAD

**Issue by pablasso** [eugen0329/vim-esearch#13]
The results order is not being respected after pressing <kbd>Shift-r</kbd>. I'm using the `pt` adapter and `nvim` as a backend.

**Comment by eugen0329** [comment]
I noticed that too. Esearch adapters only accept output from search utils that work asynchronously. I think, it rather search util responsibility than esearch adapter since it a bit complicated to handle files order. Ack have an option to sort files literally (already added as a [default](https://github.com/eugen0329/vim-esearch/commit/3b7084a9c879d2b1f1144ea7e25cc7b5955136dd#diff-29386b893bb95fa8520516e6a5b87929R4) due to lack of impact on the speed). Ag have a similar [issue](https://github.com/ggreer/the_silver_searcher/issues/107) even with PR.

**Comment by eugen0329** [comment]
@pablasso You might also notice that the results may be lost after multiple updates. This bug is also fixed in fbc3432.

**Comment by pablasso** [comment]
thanks for the heads up! it's working great now
