### ISSUE TITLE
Filetype question

### ISSUE THREAD

**Issue by ipod825** [eugen0329/vim-esearch#146]
From the document on development branch, it seems the filetype option is the file type in vim, i.e., the result of `echo &ft`. However, this is not so useful sometimes. For example, all `.h`, `.cc` and `.cpp` files have `cpp` file type in vim, which means if I want to search over only `.h` files, I am forced to search all `.cc` files at the same time.

Also, it's somehow indirect as users need to first know what type vim thinks the target files are by running `echo &ft` on the target first. For e.g., `.py` has `python` type, while in `ag`, you would just run `ag -G "py"`

**Comment by eugen0329** [comment]
Filetypes filtering feature is implemented via search utils, so there is no direct connections between `&ft` and util args. The list of supported types can be viewed using `ag --list-file-types` or the similar for other utils. In order to restrict the search to output only `.h` files, you need to specify `{'filetypes': 'hh'}` or to use globs like `{'paths': '**/*.c'}`.

Also note, that available filetypes can be hinted by using tab completion within the input, but seems, it still needs more clarification about being unrelated to `&ft` values.

**Comment by ipod825** [comment]
I see. I didn't know `ag --list-file-types`. Is it possible to add an option for file type pattern? i.e.,  `ag -G`. I am not sure if all searchers supported in esearch support file type pattern, but I think we could hide this option per user's choice of the searcher (if the searcher does not support this)?

**Comment by ipod825** [comment]
Or a even more flexible way is to add an option that takes arbitrary args list that pass directly to the searcher.

**Comment by eugen0329** [comment]
> Or a even more flexible way is to add an option that takes arbitrary args list that pass directly to the searcher.

It already can be done via unstable `g:esearch.adapters.ag.options` string. You can see the example in [readme](https://github.com/eugen0329/vim-esearch/blob/e4668e36c4cf67d806b0ca8bde29abf94fed91a1/README.md) where it's used to pass `g:sort_by_path`. But I'll probably reduce it to `g:esearch.ag.options` later.

> Is it possible to add an option for file type pattern?

It's not supported by all the utils and I decided to implement shell globs to have more generic api. I'm also going to refactor the ui to be able to pass custom menu item handlers using oneline definitions (including `-G` and `--ignore`) instead of cumbersome react-like components used right now, so it's a subject to revisit later.

**Comment by eugen0329** [comment]
I'm closing it. Please, reopen if you have any problems or suggestions.
