### ISSUE TITLE
Feature request: refresh esearch buffer

### ISSUE THREAD

**Issue by ipod825** [eugen0329/vim-esearch#147]
Description: add a function to refresh the esearch buffer by doing the search again with the same setting when it was first generated. It would be nice if the cursor can stay at a reasonable place after refresh.

Use case:   When doing some non-trivial code refactoring inside the preview panel and jumping back to the search result, I'd like to refresh the search result with the exact setting so I can check if I missed anything and move on to the next file. Without refresh, I need to quit the current buffer and do the same search again.

**Comment by eugen0329** [comment]
If there are few results and they are outputted in less than `g:esearch.early_finish_wait` timeout, the view is preserved on `R`.

If you want to keep the view regardless of the timeout, you should do `let g:esearch.win_map =[['n', 'R', '<cmd>call b:esearch.reload({"backend": "system"})<cr>']]`. It reloads with setting the runner to synchronous `system()` call instead of `jobstart()`.

**Comment by eugen0329** [comment]
Minor note: `win_map` is kind of a must now if visual-multi plugin is used, as it relies on set/reset mappings that wouldn't otherwise be restored when leaving multicursors mode. You can read about it in `:h visual-multi-compatibility`.

**Comment by ipod825** [comment]
Thanks!
