### ISSUE TITLE
[feature request] Keep only one split open, edit results, follow cursor

### ISSUE THREAD

**Issue by balta2ar** [eugen0329/vim-esearch#16]
Hello! I'd like to propose several features to be implemented. I think they would come useful in a daily routines.

1. Keep only one split open/reuse it. At the moment, when you push "S" to open a split, a new split is opened every time. I'd be nice to have an option to reuse existing window, avoid opening more splits.

2. Edit results. In addition to ESubstitute, it's nice to be able to fix code right in the search results (say, using vim-multiple-cursors), then save the search buffer to apply the fixes.

3. Follow cursor. How about adding a shortcut to switch cursor to "follow mode". Say, with a slight delay (500ms, configurable), currently selected line is opened in a split (of course they should be reused, as I mentioned in 1.). This saves keystrokes!

Thanks!

**Comment by eugen0329** [comment]
I already have a plan to implement the second. But it looks a bit complicated and unfortunately I don't have much time yet to implement it.

Concerning 1 and 3 - the both looks great! I'll check them on this weekend.

**Comment by eugen0329** [comment]
Hello,there was a lot of changes since that time, so here's what was done:
- I really like the first suggestion, so it'll be a default for opening within a tabpage. 3 can be done via API #104. It's still experimental, so proposals/suggestions are welcome, but can  it already be pretty useful as it covers most of needs associated with opening. 
Rationale:
The last suggestion would be a movement towards feature creep, as the plugin already does a lot under the hood and it's not about defining modes, unlike already existing plugins like vim-submode and others. So I believe it's gonna be more beneficial to follow the emacs way, where every action has a corresponding function that can be utilized by users and, therefore, to unlock more flexibility in crating an arbitrary number of modes (which can be done in 2 lines, see below), mappings and configurations.
Exactly your suggestion can be done using the following:
```vim
nnoremap <F4> :let g:follow = !g:follow<CR>
let g:follow = 0
au User esearch#out#win#init_post
      \  let b:open = esearch#debounce#trailing(b:esearch.open, 500)
      \| au CursorMoved <buffer> if g:follow
      \|   call b:open.invoke("vsplit", {"once": 1, "stay": 1}) | end
```

It runs vsplit by reusing a window opened earlier (reusing is done per opener command), staying in the search window. Besides the string command, opener can be a:
-  function reference
- lambda
- expression, specified using `'=expr'` format.

In addition to `once` and `stay` there are: 
- `mods` to configure the position of an opened window
- `cmdarg` to deal with `++ff`  specifiers etc. 
- `let` to specify variables or options per open call (mostly useful for setting eventignore or swapfile, but who knows what else). 

Later will be capabilities for customizing `preview()` and functions for jumps. Suchwise, the outline of the API will look like the above: a set facade-like methods with options to tweak the behavior declaratively, while also being able to build something on top of already existing features.
Please, let me know what do you think about it.
- The second suggestion is also implemented. In addition to writing, it also does some efforts to ensure the UI immutability, so you can safely do blockwise removals across files contexts or run `:substitute` without caring about matching filenames or line numbers.

All the features are in a separate branch, as they are major changes and must be properly tested first, so if you are interested to try, you can pull `development` branch.
At the moment it's more stable in general, so it won't affect your workflow.

**Comment by eugen0329** [comment]
And yeah, to encourage you to pull from dev branch even more, there are also new features besides those listed above:
- it's around 20x faster now due to parsing and rendering with lua, so the only remaining bottleneck is builtin vim mechanism to append lines
- lines contents are now colorized according to their filetypes (keywords, string/comment literals and so forth)
- enhanced paths handling: custom paths can be specified using extended globbing, project root can be detected automatically, like ctrlp and other plugins do.
- freezes are prevented completely (using separate thread for rendering, colorization for viewport only, unloading some colors and events when there're too many results, like LargeFile.vim do etc.)

**Comment by eugen0329** [comment]
Every feature is implemented and notes are in the README.md. Feel free to ask any questions regarding the usage.
