### ISSUE TITLE
Display context of search result

### ISSUE THREAD

**Issue by mz026** [eugen0329/vim-esearch#23]
Hi, thanks for building this awesome plugin!
I'm using this plugin with `git` as the search adapter. I'm wondering is there any way to make it display the search context of the search result?

When invoking `git grep` on command line, we can specify an option `-C <context-lines>` to show the adjacent lines of the matched keywords. Is it possible to the same thing with the plugin?

Thanks!

**Comment by eugen0329** [comment]
Thanks, @mz026! Glad to here that.

It's a great proposal, but it requires a lot of efforts to implement it. We need to extend parsing algorithm (a bit tedious to integrate with window life update since utils like git-grep, ag and such return output to callbacks in an arbitrary moment of time including not only a couple of lines out of `<context-lines>`, but also in the middle of the line), provide new window traversal methods (`<C-n>`, `<C-p>`, ...), establish integration with search utils (grep, ag, ack, ...), implement an interface for substitute feature and many-many more. Actually, at the moment this feature looks like a separate output module, but I need to investigate it more at first.

P.S. I already have a similar feature request, but it's more about a preview window: an automatically updating window, on the right hand of a search window (or below, it doesn't matter), that has a focus at a line of a file where the entry is located.
Would you be interested in having this feature first (not to reject, but in order to prioritize features)?

**Comment by mz026** [comment]
Hi @eugen0329 ,
Thanks for your detailed reply!
Honestly the preview window feature is not part of my current workflow :stuck_out_tongue: 
But thanks anyway!!

**Comment by ipod825** [comment]
>P.S. I already have a similar feature request, but it's more about a preview window: an automatically updating window, on the right hand of a search window (or below, it doesn't matter), that has a focus at a line of a file where the entry is located.
Would you be interested in having this feature first (not to reject, but in order to prioritize features)?

This would be a very nice feature to have. Also, as vim/newovim supports floating window now, I think this feature can be implemented using floating window.

**Comment by eugen0329** [comment]
> using floating window

It's already done :) Just press `p`

(comment is valid only for development branch at the moment).

Regarding "contexts" feature: I have a draft in a local branch with parsing contexts and it seems to be an easy task to finish the request, as the parser is rewritten. But it's not tested against all the adapters and it's not covered with tests at all yet. If it's urgent, then I'll push it into development branch. It should work at least for ag and rg.

**Comment by ipod825** [comment]
I tried both the floating window and the preview window. Floating window has a problem that it uses user's folding setting, which can make the target line invisible. However, I am not sure if this is easy to be fixed. Though both `foldnestmax` and `foldmethod` is described to be local to window in the vim doc, it actually behaves like to be local to buffer. So setting `setlocal foldnestmax=0` or `setlocal foldmethod=manual` might still overwrite user's setting once the file is open in a new window.

Preview window is nice enough for me. But currently it modifies the file's undo history as reported in #104.

**Comment by ipod825** [comment]
Oh.. I see now preview window also has the folding problem.

**Comment by eugen0329** [comment]
To use the same glossary: previews are implemented using floating windows, so in my head they was the same entity before that moment. So I assume that by saying preview you mean split opened with 'stay' option.

Both previews and splits are sneaking into alive buffer to see their "real" content with sighs, props and other things. The only exception is when you try to open a large file that is greater than N megabytes (now it's hardcoded, but later it'll be configurable), that renders only a preview context to a disposable buffer to get rid of previews that take too long to open.

Fixing folded text is relatively easy: I can add a hook unfold everything within a buffer. Actually, it looks like a candidate to become a default option.

**Comment by eugen0329** [comment]
A separate issue #106 to report problems/track status for previews.

**Comment by ipod825** [comment]
>To use the same glossary: previews are implemented using floating windows, so in my head they was the same entity before that moment. So I assume that by saying preview you mean split opened with 'stay' option.

You are right.

>Fixing folded text is relatively easy: I can add a hook unfold everything within a buffer. Actually, it looks like a candidate to become a default option.

The hard part is not to alter users' global folding setting. As I said, `foldnestmax`and `foldmanual` actually behaves as if they are local to buffer instead of window (I suppose this is a vim bug). So altering them in a preview window actually alter users' setting to the buffer.
Not sure by "hook" do you mean let the user reset the fold setting when opening the file from esearch. This seems to be an ugly solution as it shouldn't bother an user to do so.

**Comment by eugen0329** [comment]
Responded in https://github.com/eugen0329/vim-esearch/issues/106#issuecomment-602236926

**Comment by eugen0329** [comment]
Folds and broken undotree are discussed and fixed in #107.

**Comment by eugen0329** [comment]
Context can be adjusted using `<c-o>` which opens the menu and then `a`/`A`, `b`/`B` and `c`/`C` to increment/decrement them on the fly. Use `g:esearch.after`, `g:esearch.before` and `g:esearch.context` to set default values.

Please, update the plugin to pull the last changes.
