### ISSUE TITLE
Not showing results for untracked git files

### ISSUE THREAD

**Issue by ipod825** [eugen0329/vim-esearch#49]
Not sure if this was a design or not. But I found it very unhandy that vim-esearch does not show results for untracked git files. Is it possible for `e-search` showing also those results?

**Comment by eugen0329** [comment]
Hi, thanks for the report!

The thing is that some search utils that esearch use may leverage ignore files from your git repo (for example, [ag](https://github.com/ggreer/the_silver_searcher#whats-so-great-about-ag) does it). I'm not sure that we have to overrule the default behavior of them as far as it may cause some confusion for users that are familiar with those utils, so I think that adding a precaution to README.md would be a better choice here. But if you use git-grep adapter, then there is no way to search in untracked files at all (it's git-grep limitation).

In order to address your problem for `ag` (and similarly for the others) you can try this:

```vim
" Ignore VCS ignore (.gitignore, .hgignore, .svnignore; still obey .agignore)
let g:esearch#adapter#ag#options = '--skip-vcs-ignores'
```

Please, feel free to provide your questions if the snippet above won't fix your problem.
